CREATE TABLE EMP_TRAIN_SESSION (
    TRAIN_ID INT NOT NULL UNIQUE,
    EMP_ID INT NOT NULL UNIQUE,
    EMP_TRAIL_ROLE VARCHAR(50) NOT NULL ,
    TRAIN_OUTCOME VARCHAR(4) NOT NULL,
    TRAIN_EXPIRY_DATE DATE NOT NULL,
    PRIMARY KEY (Train_ID, EMP_ID),
	FOREIGN KEY (TRAIN_ID) REFERENCES TRAINING_SESSION (TRAIN_ID),
    FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID)
);

CREATE TABLE TRAINING_SESSION (
TRAIN_ID INT NOT NULL UNIQUE,
TRAIN_DATE DATE NOT NULL,
TRAIN_START_TIME TIME NOT NULL,
TRAIN_END_TIME TIME NOT NULL,
SKILL_ID INT NOT NULL UNIQUE,
PRIMARY KEY (TRAIN_ID),
FOREIGN KEY (SKILL_ID) REFERENCES SKILLS (SKILL_ID)
);
