USE CasinoDatabase;
GO

--question 5. How many Slot Attendants are scheduled today?--
SELECT COUNT(*) AS NUM_OF_SLOT_ATTENDANTS_TODAY FROM EMPLOYEE
INNER JOIN SCHEDULE ON SCHEDULE.EMP_ID = EMPLOYEE.EMP_ID
INNER JOIN EMPLOYEE_ROLE ON EMPLOYEE_ROLE.ROLE_CODE = EMPLOYEE.ROLE_CODE
WHERE ROLE_TITLE = 'Slot Attendance' AND SCHEDULE.SCH_DATE = CAST(GETDATE() AS DATE);