USE CasinoDatabase;
GO

--question 5. How many Slot Attendants are scheduled today?--
SELECT COUNT(*) AS NUM_OF_SLOT_ATTENDANTS_TODAY FROM EMPLOYEE
INNER JOIN SCHEDULE ON SCHEDULE.EMP_ID = EMPLOYEE.EMP_ID
INNER JOIN EMPLOYEE_ROLE ON EMPLOYEE_ROLE.ROLE_CODE = EMPLOYEE.ROLE_CODE
WHERE ROLE_TITLE = 'Slot Attendance' AND SCHEDULE.SCH_DATE = CAST(GETDATE() AS DATE);

--question 6. Any Slot Attendants who have not been assigned to Section NORTH in the last month?--
SELECT e.EMP_FNAME, e.EMP_LNAME, s.SCH_DATE, e.ROLE_CODE, e.EMP_ID, sh.SECT_CODE
FROM EMPLOYEE e
LEFT JOIN SCHEDULE s ON e.EMP_ID = s.EMP_ID
LEFT JOIN SHIFT sh ON sh.SCH_ID = s.SCH_ID
LEFT JOIN SECTION sec ON sec.SECT_CODE = sh.SECT_CODE
WHERE e.ROLE_CODE = 4 
AND (s.SCH_DATE IS NULL OR s.SCH_DATE >= GETDATE() OR s.SCH_DATE <= GETDATE())
AND e.EMP_ID NOT IN (
    SELECT s1.EMP_ID 
    FROM SCHEDULE s1 
    LEFT JOIN SHIFT sh1 ON sh1.SCH_ID = s1.SCH_ID 
    WHERE sh1.SECT_CODE = 1 
    AND s1.SCH_DATE BETWEEN DATEADD(month, -1, GETDATE()) AND GETDATE()
);


--Question 7. Number of active Written Warning (WW) employee A has?--
--For this question we have specified the employee with EMP_ID 10--
SELECT EMPLOYEE.EMP_FNAME, EMPLOYEE.EMP_LNAME, WRITTEN_WARNING.*
FROM EMPLOYEE
INNER JOIN WRITTEN_WARNING
ON EMPLOYEE.EMP_ID = WRITTEN_WARNING.EMP_ID
--Change the line below to choose a different employee--
WHERE EMPLOYEE.EMP_ID = 10 AND WRITTEN_WARNING.WARNING_DATE >= DATEADD(YEAR, -1, GETDATE());


--Question 8. List of active WW sorted by date and employee--
SELECT EMPLOYEE.EMP_FNAME, EMPLOYEE.EMP_LNAME, WRITTEN_WARNING.*
FROM EMPLOYEE
INNER JOIN WRITTEN_WARNING
ON EMPLOYEE.EMP_ID = WRITTEN_WARNING.EMP_ID
WHERE WRITTEN_WARNING.WW_DATE >= DATEADD(YEAR, -1, GETDATE())
ORDER BY WRITTEN_WARNING.WW_DATE, EMPLOYEE.EMP_LNAME;