USE CasinoDatabase;
GO

--question 5. How many Slot Attendants are scheduled today?--
SELECT COUNT(*) AS NUM_OF_SLOT_ATTENDANTS_TODAY FROM EMPLOYEE
INNER JOIN SCHEDULE ON SCHEDULE.EMP_ID = EMPLOYEE.EMP_ID
INNER JOIN EMPLOYEE_ROLE ON EMPLOYEE_ROLE.ROLE_CODE = EMPLOYEE.ROLE_CODE
WHERE ROLE_TITLE = 'Slot Attendance' AND SCHEDULE.SCH_DATE = CAST(GETDATE() AS DATE);

--question 6. Any Slot Attendants who have not been assigned to Section NORTH in the last month?--
SELECT EMPLOYEE.EMP_ID, EMPLOYEE.ROLE_CODE, EMPLOYEE.EMP_FNAME, EMPLOYEE.EMP_LNAME, SECTION.SECT_NAME, SCHEDULE.SCH_DATE
FROM EMPLOYEE
INNER JOIN SCHEDULE ON SCHEDULE.EMP_ID = EMPLOYEE.EMP_ID
INNER JOIN EMPLOYEE_ROLE ON EMPLOYEE_ROLE.ROLE_CODE = EMPLOYEE.ROLE_CODE
INNER JOIN SHIFT ON SHIFT.EMP_ID = EMPLOYEE.EMP_ID
INNER JOIN SECTION ON SECTION.SECT_CODE = EMPLOYEE.DEPT_ID
WHERE SCHEDULE.SCH_DATE >= DATEADD(month, -1, GETDATE())
AND EMPLOYEE_ROLE.ROLE_CODE = 4
AND EMPLOYEE.EMP_ID NOT IN (
    SELECT EMPLOYEE.EMP_ID
    FROM EMPLOYEE
    INNER JOIN SECTION ON SECTION.SECT_CODE = EMPLOYEE.DEPT_ID
    WHERE SECTION.SECT_NAME = 'NORTH'
);


--Question 7. Number of active Written Warning (WW) employee A has?--
--For this question we have specified the employee with EMP_ID 10--
SELECT EMPLOYEE.EMP_FNAME, EMPLOYEE.EMP_LNAME, WRITTEN_WARNING.*
FROM EMPLOYEE
INNER JOIN WRITTEN_WARNING
ON EMPLOYEE.EMP_ID = WRITTEN_WARNING.EMP_ID
--Change the line below to choose a different employee--
WHERE EMPLOYEE.EMP_ID = 10 AND WRITTEN_WARNING.IS_ACTIVE = 1;


--Question 8. List of active WW sorted by date and employee--
SELECT EMPLOYEE.EMP_FNAME, EMPLOYEE.EMP_LNAME, WRITTEN_WARNING.*
FROM EMPLOYEE
INNER JOIN WRITTEN_WARNING
ON EMPLOYEE.EMP_ID = WRITTEN_WARNING.EMP_ID
WHERE WRITTEN_WARNING.IS_ACTIVE = 1
ORDER BY WRITTEN_WARNING.WW_DATE, EMPLOYEE.EMP_LNAME 