CREATE TABLE LEAVE (
	LEAVE_ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	LEAVE_START DATE NOT NULL,
	LEAVE_END DATE,
	LEAVE_COMMENTS VARCHAR(20),
	EMP_ID INT NOT NULL,
	FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID),
)