CREATE TABLE SECT_SKILLS (
    SKILL_ID INT NOT NULL,
    SECT_CODE INT NOT NULL,
    PRIMARY KEY (SKILL_ID, SECT_CODE),
    FOREIGN KEY (SKILL_ID) REFERENCES SKILLS (SKILL_ID),
    FOREIGN KEY (SECT_CODE) REFERENCES SECTION (SECT_CODE)
);
