CREATE TABLE SHIFT(
    SHIFT_ID INTEGER NOT NULL,
    SHIFT_START DATE NOT NULL, 
    SHIFT_END TIME NOT NULL,
    SECT_CODE INTEGER NOT NULL,
    SCH_ID INTEGER NOT NULL,
    PRIMARY KEY(SHIFT_ID),
    FOREIGN KEY (SCH_ID) REFERENCES SCHEDULE(SCH_ID)
);