CREATE TABLE SHIFT_INVENTORY (
    SHIFT_ID INT NOT NULL,
    INV_ID INT NOT NULL,
    PRIMARY KEY (SHIFT_ID, INV_ID),
    FOREIGN KEY (SHIFT_ID) REFERENCES SHIFT(SHIFT_ID),
    FOREIGN KEY (INV_ID) REFERENCES INVENTORY(INV_ID)
)