SELECT 
    EMPLOYEE.EMP_ID, 
    EMPLOYEE.EMP_FNAME + ' ' + EMPLOYEE.EMP_LNAME AS EMP_NAME, 
    YEAR(SCHEDULE.SCH_DATE) AS YEAR, 
    DATEPART(WEEK, SCHEDULE.SCH_DATE) AS WEEK, 
    CASE 
        WHEN SUM(DATEDIFF(MINUTE, SHIFT.SHIFT_START, CASE WHEN SHIFT.SHIFT_END < SHIFT.SHIFT_START THEN DATEADD(HOUR, 24, SHIFT.SHIFT_END) ELSE SHIFT.SHIFT_END END) / 60.0) BETWEEN -24 AND -12 
        THEN SUM(DATEDIFF(MINUTE, SHIFT.SHIFT_START, CASE WHEN SHIFT.SHIFT_END < SHIFT.SHIFT_START THEN DATEADD(HOUR, 24, SHIFT.SHIFT_END) ELSE SHIFT.SHIFT_END END) / 60.0) + 24 

		WHEN SUM(DATEDIFF(MINUTE, SHIFT.SHIFT_START, CASE WHEN SHIFT.SHIFT_END < SHIFT.SHIFT_START THEN DATEADD(HOUR, 24, SHIFT.SHIFT_END) ELSE SHIFT.SHIFT_END END) / 60.0) BETWEEN -12 AND 0 
		THEN SUM(DATEDIFF(MINUTE, SHIFT.SHIFT_START, CASE WHEN SHIFT.SHIFT_END < SHIFT.SHIFT_START THEN DATEADD(HOUR, 24, SHIFT.SHIFT_END) ELSE SHIFT.SHIFT_END END) / 60.0) + 24 

        ELSE SUM(DATEDIFF(MINUTE, SHIFT.SHIFT_START, CASE WHEN SHIFT.SHIFT_END < SHIFT.SHIFT_START THEN DATEADD(HOUR, 24, SHIFT.SHIFT_END) ELSE SHIFT.SHIFT_END END) / 60.0) 
    END AS HOURS_WORKED
FROM 
    EMPLOYEE
    INNER JOIN SHIFT ON EMPLOYEE.EMP_ID = SHIFT.EMP_ID
    INNER JOIN SCHEDULE ON SHIFT.SCH_ID = SCHEDULE.SCH_ID
GROUP BY 
    EMPLOYEE.EMP_ID, 
    EMPLOYEE.EMP_FNAME, 
    EMPLOYEE.EMP_LNAME, 
    YEAR(SCHEDULE.SCH_DATE), 
    DATEPART(WEEK, SCHEDULE.SCH_DATE);

--Question 2: Number of labor hours last week?
SELECT 
    EMPLOYEE.EMP_ID, 
    EMPLOYEE.EMP_FNAME + ' ' + EMPLOYEE.EMP_LNAME AS EMP_NAME, 
    YEAR(DATEADD(WEEK, -1, SCHEDULE.SCH_DATE)) AS YEAR, 
    DATEPART(WEEK, DATEADD(WEEK, -1, SCHEDULE.SCH_DATE)) AS WEEK, 
    CASE 
        WHEN SUM(DATEDIFF(MINUTE, SHIFT.SHIFT_START, CASE WHEN SHIFT.SHIFT_END < SHIFT.SHIFT_START THEN DATEADD(HOUR, 24, SHIFT.SHIFT_END) ELSE SHIFT.SHIFT_END END) / 60.0) BETWEEN -24 AND -12 
        THEN SUM(DATEDIFF(MINUTE, SHIFT.SHIFT_START, CASE WHEN SHIFT.SHIFT_END < SHIFT.SHIFT_START THEN DATEADD(HOUR, 24, SHIFT.SHIFT_END) ELSE SHIFT.SHIFT_END END) / 60.0) + 24 

        WHEN SUM(DATEDIFF(MINUTE, SHIFT.SHIFT_START, CASE WHEN SHIFT.SHIFT_END < SHIFT.SHIFT_START THEN DATEADD(HOUR, 24, SHIFT.SHIFT_END) ELSE SHIFT.SHIFT_END END) / 60.0) BETWEEN -12 AND 0 
        THEN SUM(DATEDIFF(MINUTE, SHIFT.SHIFT_START, CASE WHEN SHIFT.SHIFT_END < SHIFT.SHIFT_START THEN DATEADD(HOUR, 24, SHIFT.SHIFT_END) ELSE SHIFT.SHIFT_END END) / 60.0) + 12 

        ELSE SUM(DATEDIFF(MINUTE, SHIFT.SHIFT_START, CASE WHEN SHIFT.SHIFT_END < SHIFT.SHIFT_START THEN DATEADD(HOUR, 24, SHIFT.SHIFT_END) ELSE SHIFT.SHIFT_END END) / 60.0) 
    END AS HOURS_WORKED
FROM 
    EMPLOYEE
    INNER JOIN SHIFT ON EMPLOYEE.EMP_ID = SHIFT.EMP_ID
    INNER JOIN SCHEDULE ON SHIFT.SCH_ID = SCHEDULE.SCH_ID
WHERE
    SCHEDULE.SCH_DATE BETWEEN DATEADD(WEEK, -1, GETDATE()) AND GETDATE()
GROUP BY 
    EMPLOYEE.EMP_ID, 
    EMPLOYEE.EMP_FNAME, 
    EMPLOYEE.EMP_LNAME, 
    YEAR(DATEADD(WEEK, -1, SCHEDULE.SCH_DATE)), 
    DATEPART(WEEK, DATEADD(WEEK, -1, SCHEDULE.SCH_DATE));