CREATE TABLE WRITTEN_WARNING (
	WW_ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	WW_DATE DATE NOT NULL,
	WW_OFFENCE VARCHAR(20) NOT NULL,
	WW_COMMENTS VARCHAR(20) NOT NULL,
	EMP_ID INT NOT NULL,
	FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID),
	)